language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
deploy:
  provider: npm
  email: hadaszeilberger@gmail.com
  api_key:
    secure: qg/75hBj7lGkgKt2kuX7uGWQrKhqYLjqQPsDobVkMcnPNGprO8LRYUDDSPMvFbjSeiqdGdwdFgspkOYEljf1vlyS+N3huGm4Hj+WoEe/BW7lZZWROmrQamLChGuZ3H0iFL1SHLe32Ly+7mNvZ9hREPxozPgLRSYLDd+chtxCvvcErO2YFqcKCLjCso3kbDQXO24pbMpD42+ZJEJke0NLBNvbNJ16LG6o3nbvuAVRWd8zWgYafMAbZTbl9bqqXXf+pOf2z2zGtYxVN+rZE7XCW4J3nX4Ya/e1ymyHetugoeTtfxG05HCg5bguznYxJTJaMJSWiQNNCnTQELexZwyTLSPyYsw0dSvf57QSHGyQwxzqadcANn9O6JL6NNROBhpAM6sD52qDBxB9BBEsUwEtXQKMbEOTBQaIHdMKtZMZyinW77/m6XtTzwlmB9CsDN3fUDWAknqY+2foCioZeZvvvGWAbjJQ9eUQL1BUw+/hHtY7cOyvDC1ah4ljnUnIddKlNvZBBxWJbjU7x5S2zhjaayExPaxpd2k/f8RkcxB7URvdCbbxsrzieQ2OPer0ywHAOvyQyFTHtcE3x6PzUeB+dBGkBlS9jMKrR+7HmBp5FafD//uW1k/kMAh3HDkv0THYSYbeNgpmYXRZDLMx45st8SXmoZHF4oNoTHhBxSP5mMo=
  on:
    branch: develop
    tags: true
